# Generated by Django 4.2.6 on 2024-01-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dependente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('clientes', models.ManyToManyField(related_name='antendente_cliente', to='app.cliente')),
            ],
        ),
    ]
